# Generated by Django 6.0 on 2025-12-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_payment_provider_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Full address for delivery', null=True),
        ),
    ]
