# Generated by Django 6.0 on 2026-01-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wc_order_id',
            field=models.CharField(blank=True, help_text='WooCommerce Order ID', max_length=50, null=True),
        ),
    ]
