# Generated by Django 6.0 on 2026-01-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wc_id',
            field=models.IntegerField(blank=True, help_text='WooCommerce Product ID', null=True, unique=True),
        ),
    ]
