# Generated by Django 6.0 on 2026-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_wc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wc_order_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wc_id',
        ),
        migrations.AddField(
            model_name='order',
            name='external_order_id',
            field=models.CharField(blank=True, help_text='External system order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='external_source',
            field=models.CharField(blank=True, default='', help_text="Source: 'woocommerce', 'custom_erp', etc.", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, help_text='External system ID (WooCommerce, ERP, etc.)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_source',
            field=models.CharField(blank=True, default='', help_text="Source system: 'woocommerce', 'custom_erp', etc.", max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PICKER', 'Warehouse Picker'), ('DRIVER', 'Delivery Agent'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
